= Lab 1 - Getting Started with Spring Boot

== Bootstrap the Project

. In your browser, visit http://start.spring.io.

. Click on the *Switch to the full version* link.

. Fill out the *Project metadata* fields as follows:
+
Group:: `io.pivotal.spring`
Artifact:: `hello-spring-boot`
Name:: `hello-spring-boot`
Description:: `Hello Spring Boot`
Package Name:: `io.pivotal.spring.hello`
Packaging:: Jar
Java Version:: 1.8
Language:: Java

. In the *Project dependencies* section, check the following:
+
* Web

. Click the *Generate Project* button. Your browser will download a zip file.
Unpack that zip file at `$COURSE_HOME/labs/initial`.

. Import the project's `pom.xml` into your editor/IDE of choice.

. Add a `@RestController` annotation to the class `io.pivotal.spring.hello.HelloSpringBootApplication`.

. Add the following request handler to the class `io.pivotal.spring.hello.HelloSpringBootApplication`:
+
[source,java]
----
@RequestMapping("/")
public String hello() {
    return "Hello World!";
}
----

== Build and Run with Embedded Apache Tomcat

Spring Boot will embed Apache Tomcat by default.

. Build the application:
+
----
$ mvn package
----

. Run the application:
+
----
$ java -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar
----
+
You should see the application start up an embedded Apache Tomcat server on port 8080:
+
----
2015-05-03 13:20:51.690  INFO 2465 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2015-05-03 13:20:51.691  INFO 2465 --- [           main] i.p.s.hello.HelloSpringBootApplication   : Started HelloSpringBootApplication in 3.023 seconds (JVM running for 3.432)
----

. Visit the application in the browser (http://localhost:8080), and you should see the following:
+
----
Hello World!
----

